apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8learnings
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: k8backend
  template: 
    metadata:
      labels:
        app: k8backend
    spec:
      containers: 
      - name: backend
        image: tishathakral/k8learnings-backend
        ports: 
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: k8learnings-service
spec: 
  selector:
    app: k8backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP