apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8learnings-frontend
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: k8frontend
  template: 
    metadata:
      labels:
        app: k8frontend
    spec:
      containers: 
      - name: frontend
        image: tishathakral/k8learnings-frontend
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: k8learnings-frontend-service
spec: 
  selector:
    app: k8frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
